export const SCORING_WEIGHTS = {
  MULANK_FRIENDLY: 25,
  BHAGYANK_FRIENDLY: 20,
  KUA_FRIENDLY: 15,
  FILLS_MISSING_NUMBER: 10,
  ACTIVATES_PLANE: 15,
  CONFLICT_OVERLOADED: -15,
  HOSTILE_COMPATIBILITY: -25,
  PHONETIC_QUALITY: 15
};

export const THRESHOLDS = {
  OVERLOAD: 3,
  DOMINANT: 2
};
